### ISSUE TITLE
problems about ploting boundingbox

### ISSUE THREAD

**Issue by georgeokelly** [kyo055/ncnn_yolo2#3]
您好，我根据您的code在Linux环境实现的tiny yolo voc with ncnn。但是bounding box有些问题：

![a](https://user-images.githubusercontent.com/34239051/39987827-5bec8800-5798-11e8-977c-019b175e99ff.png)

请问您知道如何解决吗

**Comment by kyo055** [comment]
@georgeokelly 我也遇到了这个问题，给的定位框会向上偏移，我一开始以为是anchors出了问题，但是有一些图片就没有这种情况，我打印了很多ncnn对应pytorch中mat来看了一下，发现ncnn转了pytorch的模型后有一些精度损失，我想也可能是这些精度损失造成的，或者是我在做tranpose操作的时候移位有问题。 你可以研究一下这里。

**Comment by zhyj3038** [comment]
请问这个问题有改进吗？ 
我以前做caffe版本的faster rcnn时候，虽然有精度损失，然而不会有这么大的偏移。您这个结果感觉偏移量太大了

**Comment by kyo055** [comment]
@zhyj3038  这个很可能是padding的问题，我自己最近一直在忙其他的也没有 在改进这里， 其实训练的模型应该可以改变 来更适应ncnn的padding方式
